package encryption

const ErrEncryptionWrongPassword = "EncryptionWrongPasswordError"
const ErrEncryptionCypherTooShort = "EncryptionCypherTooShortError"
const ErrEncryptionBase64DecodeFailed = "EncryptionBase64DecodeFailedError"